# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "D-Walter"
repo_name: "mot-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: "./docs/cv-arxiv-daily.json"
json_gitpage_path: "./docs/cv-arxiv-daily-web.json"
json_wechat_path: "./docs/cv-arxiv-daily-wechat.json"

md_readme_path: "README.md"
md_gitpage_path: "./docs/index.md"
md_wechat_path: "./docs/wechat.md"

# keywords to search
keywords:
  "Hyperspectral":
    filters:
      [
        "Hyperspectral",
        "Hyper-spectral",
      ]
    interesting_keywords:
  "MOT":
    filters:
      [
        "MOT",
        "MTT",
        "Multiple Object Tracking",
        "Multiple Target Tracking",
        "Multi-Object Tracking",
        "Multi-Target Tracking",
      ]
    interesting_keywords:
      TBD: ["Track by detection", "Track-by-detection", "TBD"]
      JDE: ["JDE", "Joint Detection and Embedding"]
      End to end: ["End to end", "End-to-end"]
